version: "3.5"

services:
  jupyter:
    image: jupyter/tensorflow-notebook
    container_name: dako-k22
    volumes:
      - ./notebooks:/home/jovyan/notebooks:z # jovyan is the default user
    ports:
      - 8888:8888
    command: "start-notebook.sh --ServerApp.token=''"

